# Generated by Django 2.2.10 on 2020-05-15 19:49

from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas_beme', '0003_auto_20200515_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraparte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contraparte', to='personas_beme.Persona')),
                ('gestor_sin_acceso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gestor_sin_acceso', to='personas_beme.Persona')),
            ],
            options={
                'verbose_name': 'Contrapartes',
                'verbose_name_plural': 'Contrapartes',
            },
        ),
        migrations.CreateModel(
            name='ActualizaGestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('info_gestion', models.FileField(blank=True, help_text='Debe ser el archivo de gestión', null=True, upload_to=gestion.models.user_directory_path)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Gestor', to='personas_beme.Persona')),
            ],
            options={
                'verbose_name': 'Actualizador de Gestión',
                'verbose_name_plural': 'Actualizados de Gestión',
            },
        ),
    ]
