# Generated by Django 3.0.4 on 2020-06-04 20:11

from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas_beme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizaGestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('info_gestion', models.FileField(blank=True, help_text='Debe ser el archivo de gestión', max_length=500, null=True, upload_to=gestion.models.user_directory_path)),
                ('gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Gestor', to='personas_beme.Persona')),
            ],
            options={
                'verbose_name': 'Actualizador de Gestión',
                'verbose_name_plural': 'Actualizados de Gestión',
            },
        ),
        migrations.CreateModel(
            name='Contraparte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraparte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraparte', to='personas_beme.Persona')),
                ('gestor_sin_acceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_sin_acceso', to='personas_beme.Persona')),
            ],
            options={
                'verbose_name': 'Contrapartes',
                'verbose_name_plural': 'Contrapartes',
                'unique_together': {('gestor_sin_acceso', 'contraparte')},
            },
        ),
    ]
