# Generated by Django 2.2.10 on 2020-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizagestion',
            name='info_gestion',
            field=models.FileField(blank=True, help_text='Debe ser el archivo de gestión del ejecutivo', null=True, upload_to='gestiones/12-05-2020'),
        ),
    ]
