# Generated by Django 2.2.10 on 2020-05-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActualizaGestion',
        ),
    ]
