# Generated by Django 2.2.10 on 2020-05-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_actualizagestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizagestion',
            name='gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Gestor', to='personas_beme.Persona'),
        ),
        migrations.AlterField(
            model_name='contraparte',
            name='contraparte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraparte', to='personas_beme.Persona'),
        ),
        migrations.AlterField(
            model_name='contraparte',
            name='gestor_sin_acceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_sin_acceso', to='personas_beme.Persona'),
        ),
    ]
