# Generated by Django 2.2.10 on 2020-05-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas_beme', '0004_auto_20200518_1804'),
        ('gestion', '0004_auto_20200520_1312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contraparte',
            unique_together={('gestor_sin_acceso', 'contraparte')},
        ),
    ]
