# Generated by Django 2.2.10 on 2020-04-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codigo_ejecutivo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(choices=[('ASESOR', 'Asesor Comercial de Riesgo'), ('EJECUTIVO_COMERCIAL', 'Ejecutivo Comercial'), ('ASISTENTE_COMERCIAL', 'Asistente Comercial')], max_length=30)),
                ('zona', models.CharField(choices=[('ZONA_NORTE', 'Zona Norte'), ('ZONA_CENTRO', 'Zona Centro'), ('ZONA_SUR', 'Zona Sur')], max_length=15)),
                ('modulo', models.CharField(choices=[('XV_REGION', 'NORTE: XV Región'), ('I_REGION', 'NORTE: I Región'), ('II_REGION', 'NORTE: II Región'), ('III_REGION', 'NORTE: III Región'), ('IV_REGION', 'NORTE: IV Región'), ('V_REGION_COSTA', 'NORTE: V Región Costa'), ('V_REGION_CORDILLERA', 'NORTE: V Región Cordillera'), ('VI_REGION', 'NORTE: VI Región'), ('METROPOLITANA_PONIENTE', 'CENTRO: Metropolitana Poniente'), ('METROPOLITANA_ORIENTE', 'CENTRO: Metropolitana Oriente'), ('METROPOLITANA_SUR', 'CENTRO: Metropolitana Sur'), ('METROPOLITANA_CENTRO', 'CENTRO: Metropolitana Centro'), ('METROPOLITANA_NORTE', 'CENTRO: Metropolitana Norte'), ('VII_REGION', 'SUR: VII Región'), ('BIOBIO_NORTE', 'SUR: Bío Bío Norte'), ('BIOBIO_SUR', 'SUR: Bío Bío Sur'), ('VIII_REGION_CORDILLERA', 'SUR: VIII Región Cordillera'), ('IX_REGION_NORTE', 'SUR: IX Región Norte'), ('IX_REGION_SUR', 'SUR: IX Región Sur'), ('XIV_REGION', 'SUR: XIV Región'), ('X_REGION', 'SUR: X Región'), ('XI_REGION', 'SUR: XI Región'), ('XII_REGION', 'SUR: XII Región')], max_length=30)),
                ('sucursal', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('CASA_SIN_VDI', 'En casa sin acceso remoto'), ('CASA_CON_VDI', 'En casa con acceso remoto'), ('EN_SUCURSAL', 'En Sucursal')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personas_beme.persona',),
        ),
        migrations.CreateModel(
            name='AsistenteComercial',
            fields=[
            ],
            options={
                'verbose_name': 'Asistente Comercial',
                'verbose_name_plural': 'Asistentes Comerciales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personas_beme.persona',),
        ),
        migrations.CreateModel(
            name='EjecutivoComercial',
            fields=[
            ],
            options={
                'verbose_name': 'Ejecutivo Comercial',
                'verbose_name_plural': 'Ejecutivos Comerciales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personas_beme.persona',),
        ),
    ]
