# Generated by Django 2.2.10 on 2020-05-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas_beme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cargo',
            field=models.CharField(choices=[('ASESOR_COMERCIAL', 'Asesor Comercial de Riesgo'), ('EJECUTIVO_COMERCIAL', 'Ejecutivo Comercial'), ('ASISTENTE_COMERCIAL', 'Asistente Comercial')], max_length=30),
        ),
    ]
