# Generated by Django 3.0.4 on 2020-06-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas_beme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='codigo_sucursal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
