# Generated by Django 3.0.4 on 2020-06-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas_beme', '0002_persona_codigo_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['codigo_persona_beme']},
        ),
    ]
