# Generated by Django 2.2.10 on 2020-05-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas_beme', '0003_auto_20200515_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='codigo_persona_beme',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
