# Generated by Django 2.2.10 on 2020-05-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('dop_num_ope', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Operación')),
                ('ope_cant_cuo', models.IntegerField(verbose_name='Plazo')),
                ('dop_mnt_cuo', models.IntegerField(verbose_name='Monto Cuota')),
                ('dop_sdo_tot', models.IntegerField(verbose_name='Saldo Total')),
                ('ope_tasa', models.FloatField(verbose_name='Tasa')),
                ('ope_valor_tasa_penal', models.FloatField(verbose_name='Tasa Penal')),
                ('ope_cuotas_pagadas', models.IntegerField(verbose_name='Cuotas Pagadas')),
                ('dop_dia_mra', models.IntegerField(verbose_name='Días de Mora')),
                ('fecha_curse', models.DateField(blank=True, verbose_name='Fecha Curse')),
                ('fec_oto', models.DateField(blank=True, verbose_name='Fecha Otorgación')),
                ('primer_ven', models.DateField(blank=True, verbose_name='Primer Vencimiento')),
                ('prox_ven', models.DateField(blank=True, verbose_name='Próximo Vencimiento')),
                ('fecha_pago_final', models.DateField(blank=True)),
                ('familia', models.CharField(choices=[('MR', 'MR'), ('M', 'M'), ('MG', 'MG'), ('MRG', 'MRG'), ('RP', 'RP'), ('MF', 'MF'), ('TC', 'TC'), ('LCC', 'LCC'), ('LCK', 'LCK'), ('MRF', 'MRF'), ('NRJ', 'NRJ'), ('CV', 'CV'), ('CK', 'CK')], max_length=20)),
                ('cpd', models.CharField(max_length=5)),
                ('marca', models.CharField(choices=[('C', 'C'), ('K', 'K')], max_length=20, verbose_name='Tipo de Crédito')),
                ('perfil_de_riesgo', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
            },
        ),
        migrations.CreateModel(
            name='ImpactoOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_impacto', models.DateField()),
                ('cant_ope', models.IntegerField(default=1)),
                ('plazo_restante', models.IntegerField(default=1)),
                ('tasa_seguro', models.FloatField(blank=True, default=0, null=True)),
                ('interes_moratorio', models.IntegerField(default=1)),
                ('gastos_cobranza', models.IntegerField(default=0)),
                ('comision_prep', models.IntegerField(default=0)),
                ('periodo_de_gracia', models.IntegerField(default=0)),
                ('saldo_adeudado_gar_final', models.IntegerField(default=0)),
                ('saldo_sin_gar_comercial', models.IntegerField(blank=True, default=0, null=True)),
                ('saldo_sin_gar_comercial_final', models.IntegerField(blank=True, default=0, null=True)),
                ('saldo_adeudado_consumo', models.IntegerField(blank=True, default=0, null=True)),
                ('pago_mensual', models.IntegerField(default=0)),
                ('ope_tasa_media', models.FloatField(default=0)),
                ('total_a_pagar_hoy', models.IntegerField(default=0)),
                ('perfil_riesgo', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Impacto de Operacion',
                'verbose_name_plural': 'Impacto de Operaciones',
            },
        ),
    ]
