# Generated by Django 2.2.10 on 2020-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactooperacion',
            name='tasa_seguro',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
