# Generated by Django 2.2.10 on 2020-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_consumo_final',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_gar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_gar_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_gar_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_gar_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_gar_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_gar_final_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_gar_final_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_gar_final_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='saldo_adeudado_gar_final_4',
            field=models.IntegerField(default=0),
        ),
    ]
