# Generated by Django 2.2.10 on 2020-05-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_auto_20200510_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactooperacion',
            old_name='saldo_adeudado_gar_final_1',
            new_name='saldo_adeudado_gar_1_final',
        ),
        migrations.RenameField(
            model_name='impactooperacion',
            old_name='saldo_adeudado_gar_final_2',
            new_name='saldo_adeudado_gar_2_final',
        ),
        migrations.RenameField(
            model_name='impactooperacion',
            old_name='saldo_adeudado_gar_final_3',
            new_name='saldo_adeudado_gar_3_final',
        ),
        migrations.RenameField(
            model_name='impactooperacion',
            old_name='saldo_adeudado_gar_final_4',
            new_name='saldo_adeudado_gar_4_final',
        ),
    ]
