# Generated by Django 2.2.10 on 2020-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_auto_20200510_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='ope_monto_origen_pes',
            field=models.IntegerField(default=0, verbose_name='Monto Origen'),
            preserve_default=False,
        ),
    ]
