# Generated by Django 2.2.10 on 2020-05-08 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_auto_20200430_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactooperacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='impacto_operaciones', to='clientes.Cliente'),
        ),
    ]
