# Generated by Django 2.2.10 on 2020-05-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_auto_20200508_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactooperacion',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Cliente'),
        ),
    ]
