# Generated by Django 2.2.10 on 2020-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_operacion_ope_monto_origen_pes'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='eficacia_gar',
            field=models.FloatField(default=0, verbose_name='Eficacia de la Garantía'),
            preserve_default=False,
        ),
    ]
