# Generated by Django 2.2.10 on 2020-05-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_operacion_eficacia_gar'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactooperacion',
            name='num_cuotas_max_fogape_gar_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='num_cuotas_max_fogape_gar_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='num_cuotas_max_fogape_gar_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='num_cuotas_max_fogape_gar_4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='impactooperacion',
            name='num_cuotas_max_k',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
