# Generated by Django 2.2.10 on 2020-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_auto_20200513_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='ope_valor_tasa_penal',
        ),
        migrations.AddField(
            model_name='operacion',
            name='ope_tasa_penal_diaria',
            field=models.FloatField(default=0, verbose_name='Tasa Penal Diaria'),
            preserve_default=False,
        ),
    ]
