# Generated by Django 2.2.10 on 2020-05-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_auto_20200520_1312'),
        ('operaciones', '0008_auto_20200520_1250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='impactooperacion',
            unique_together={('cliente', 'fecha_de_impacto')},
        ),
    ]
