# Generated by Django 2.2.10 on 2020-04-29 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas_beme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_rut', models.IntegerField(help_text='Sin dígito verificador', primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateField(blank=True)),
                ('fecha_gestion', models.DateField(blank=True)),
                ('contactabilidad', models.CharField(blank=True, choices=[('CON_CONTACTO', 'Contactado'), ('SIN_CONTACTO', 'Sin Contacto')], max_length=30)),
                ('respuesta', models.CharField(blank=True, choices=[('INTERESADO_EN_OFERTA', 'Interesado en Oferta Simulador'), ('INTERESADO_EN_RENEGOCIAR', 'Interesado en Renegociar - Derivar a la Plataforma BEME'), ('NO_INTERESADO-PAGARA_CUOTA', 'No Interesado - Pagará Cuota')], max_length=30)),
                ('estado', models.CharField(blank=True, choices=[('SE_ACERCARA', 'Se acercará a la Sucursal'), ('NO_SE_ACERCARA', 'No puede acercarse a la Sucursal'), ('LO_PENSARA', 'Lo Pensará')], max_length=30)),
                ('fecha_reinsistencia', models.DateField(blank=True)),
                ('estado_contacto_interesado', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('SIN_CONTACTO', 'Sin Contacto')], max_length=30)),
                ('estado_cliente', models.CharField(blank=True, choices=[('FIMARA', 'Firmará Documentos'), ('DOCUMENTOS_FIRMADOS', 'Documentos Firmados'), ('RECHAZA_OFERTA', 'Rechaza Oferta')], max_length=30)),
                ('fecha_firma', models.DateField(blank=True)),
                ('estado_curse', models.CharField(blank=True, choices=[('NO_CURSADA', 'No Cursada'), ('CURSADA', 'Cursada'), ('EN_PROCESO', 'En Proceso')], max_length=30)),
                ('zona_cli', models.CharField(choices=[('ZONA_NORTE', 'Zona Norte'), ('ZONA_CENTRO', 'Zona Centro'), ('ZONA_SUR', 'Zona Sur')], max_length=30)),
                ('modulo_cli', models.CharField(choices=[('XV_REGION', 'NORTE: XV Región'), ('I_REGION', 'NORTE: I Región'), ('II_REGION', 'NORTE: II Región'), ('III_REGION', 'NORTE: III Región'), ('IV_REGION', 'NORTE: IV Región'), ('V_REGION_COSTA', 'NORTE: V Región Costa'), ('V_REGION_CORDILLERA', 'NORTE: V Región Cordillera'), ('VI_REGION', 'NORTE: VI Región'), ('METROPOLITANA_PONIENTE', 'CENTRO: Metropolitana Poniente'), ('METROPOLITANA_ORIENTE', 'CENTRO: Metropolitana Oriente'), ('METROPOLITANA_SUR', 'CENTRO: Metropolitana Sur'), ('METROPOLITANA_CENTRO', 'CENTRO: Metropolitana Centro'), ('METROPOLITANA_NORTE', 'CENTRO: Metropolitana Norte'), ('VII_REGION', 'SUR: VII Región'), ('BIOBIO_NORTE', 'SUR: Bío Bío Norte'), ('BIOBIO_SUR', 'SUR: Bío Bío Sur'), ('VIII_REGION_CORDILLERA', 'SUR: VIII Región Cordillera'), ('IX_REGION_NORTE', 'SUR: IX Región Norte'), ('IX_REGION_SUR', 'SUR: IX Región Sur'), ('XIV_REGION', 'SUR: XIV Región'), ('X_REGION', 'SUR: X Región'), ('XI_REGION', 'SUR: XI Región'), ('XII_REGION', 'SUR: XII Región')], max_length=30)),
                ('sucursal_cli', models.CharField(choices=[('SUBGERENCIA_REGIONAL_XV_REGION', 'NORTE: Subgerencia Regional XV Región'), ('ARICA', 'NORTE: Arica'), ('ARICA_SANTA_MARIA', 'NORTE: Arica Santa María'), ('SUBGERENCIA_REGIONAL_RM_CENTRO', 'CENTRO: Subgerencial Regional RM Centro'), ('DIEZ_DE_JULIO', 'CENTRO: Diez de Julio'), ('SANTIAGO_PRINCIPAL', 'CENTRO: Santiago Principal'), ('SANTIAGO_JOSE_MARIA_CARO', 'CENTRO: Santiago José María Caro'), ('MATUCANA', 'CENTRO: Matucana'), ('ESTACION_CENTRAL', 'CENTRO: Estación Central'), ('SANTIAGO_SAN_DIEGO', 'CENTRO: Santiago San Diego'), ('PASEO_HUERFANOS', 'CENTRO: Paseo Huerfanos'), ('SANTIAGO_SERVIESTADO', 'CENTRO: Santiago ServiEstado'), ('SANTIAGO_LA_LEGUA', 'CENTRO: Santiago La Legua'), ('SANTA_LUCIA', 'CENTRO: Santa Lucía'), ('AVENIDA_MATTA', 'CENTRO: Avenida Matta'), ('BANDERA', 'CENTRO: Bandera'), ('PASEO_ESTADO', 'CENTRO: Paseo Estado'), ('VICUÑA_MACKENNA', 'CENTRO: Vicuña Mackenna'), ('SANTA_ANA', 'CENTRO: Santa Ana'), ('CENTRO_DE_ATENCION_DIGITAL', 'CENTRO: Centro de Atención Digital La Moneda'), ('LO_ESPEJO', 'CENTRO: Lo Espejo'), ('PLATAFORMA_REMOTA', 'CENTRO: Plataforma Remota Microempresas'), ('SUBGERENCIA_REGIONAL_VII_REGION', 'SUR: Subgerencia Regional VII Región'), ('TALCA', 'SUR: Talca'), ('LINARES', 'SUR: LINARES')], max_length=50)),
                ('tel_fijo_1', models.IntegerField(blank=True, help_text='+56 + (cod reg) + (num)', null=True)),
                ('tel_fijo_2', models.IntegerField(blank=True, help_text='+56 + (cod reg) + (num)', null=True)),
                ('tel_cel_1', models.IntegerField(blank=True, help_text='+569 + (123456789)')),
                ('tel_cel_2', models.IntegerField(blank=True, help_text='+569 + (123456789)')),
                ('direccion_particular', models.CharField(blank=True, max_length=100)),
                ('direccion_comercial', models.CharField(blank=True, max_length=100)),
                ('ejecutivo_cartera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pertenece_a_la_cartera', to='personas_beme.EjecutivoComercial')),
                ('ejecutivo_gestor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actualmente_gestionando', to='personas_beme.EjecutivoComercial')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_oferta', models.DateField()),
                ('ope_tasa_oferta_1', models.FloatField(default=0)),
                ('plazo_oferta_1', models.IntegerField(default=1)),
                ('monto_oferta_1', models.IntegerField(default=0)),
                ('per_rebaja_oferta_1', models.FloatField(default=0)),
                ('total_a_pagar_oferta_1', models.IntegerField(default=0)),
                ('ope_tasa_oferta_2', models.FloatField(default=0)),
                ('plazo_oferta_2', models.IntegerField(default=1)),
                ('monto_oferta_2', models.IntegerField(default=0)),
                ('per_rebaja_oferta_2', models.FloatField(default=0)),
                ('total_a_pagar_oferta_2', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Oferta Cliente',
                'verbose_name_plural': 'Ofertas Clientes',
                'unique_together': {('fecha_de_oferta', 'cliente')},
            },
        ),
    ]
