# Generated by Django 2.2.10 on 2020-05-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas_beme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_rut', models.IntegerField(help_text='Sin dígito verificador', primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(max_length=100)),
                ('zona_cli', models.CharField(choices=[('ZONA_NORTE', 'Zona Norte'), ('ZONA_CENTRO', 'Zona Centro'), ('ZONA_SUR', 'Zona Sur')], max_length=30)),
                ('modulo_cli', models.CharField(choices=[('XV_REGION', 'NORTE: XV Región'), ('I_REGION', 'NORTE: I Región'), ('II_REGION', 'NORTE: II Región'), ('III_REGION', 'NORTE: III Región'), ('IV_REGION', 'NORTE: IV Región'), ('V_REGION_COSTA', 'NORTE: V Región Costa'), ('V_REGION_CORDILLERA', 'NORTE: V Región Cordillera'), ('VI_REGION', 'NORTE: VI Región'), ('METROPOLITANA_PONIENTE', 'CENTRO: Metropolitana Poniente'), ('METROPOLITANA_ORIENTE', 'CENTRO: Metropolitana Oriente'), ('METROPOLITANA_SUR', 'CENTRO: Metropolitana Sur'), ('METROPOLITANA_CENTRO', 'CENTRO: Metropolitana Centro'), ('METROPOLITANA_NORTE', 'CENTRO: Metropolitana Norte'), ('VII_REGION', 'SUR: VII Región'), ('BIOBIO_NORTE', 'SUR: Bío Bío Norte'), ('BIOBIO_SUR', 'SUR: Bío Bío Sur'), ('VIII_REGION_CORDILLERA', 'SUR: VIII Región Cordillera'), ('IX_REGION_NORTE', 'SUR: IX Región Norte'), ('IX_REGION_SUR', 'SUR: IX Región Sur'), ('XIV_REGION', 'SUR: XIV Región'), ('X_REGION', 'SUR: X Región'), ('XI_REGION', 'SUR: XI Región'), ('XII_REGION', 'SUR: XII Región')], max_length=30)),
                ('sucursal_cli', models.CharField(max_length=50)),
                ('tel_fijo_1', models.IntegerField(blank=True, help_text='+56 + (cod reg) + (num)', null=True)),
                ('tel_fijo_2', models.IntegerField(blank=True, help_text='+56 + (cod reg) + (num)', null=True)),
                ('tel_cel_1', models.IntegerField(blank=True, help_text='+569 + (123456789)')),
                ('tel_cel_2', models.IntegerField(blank=True, help_text='+569 + (123456789)')),
                ('direccion_particular', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_comercial', models.CharField(blank=True, max_length=100, null=True)),
                ('impacto_gasto', models.IntegerField()),
                ('fecha_asignacion', models.DateField(blank=True)),
                ('fecha_gestion', models.DateField(blank=True)),
                ('respuesta', models.CharField(blank=True, choices=[('INTERESADO_EN_OFERTA', 'Interesado en Oferta Simulador'), ('INTERESADO_EN_RENEGOCIAR', 'Interesado en Renegociar - Derivar a la Plataforma BEME'), ('NO_INTERESADO-PAGARA_CUOTA', 'No Interesado - Pagará Cuota')], max_length=30, null=True)),
                ('fecha_reinsistencia', models.DateField(blank=True)),
                ('estado_contacto_interesado', models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('SIN_CONTACTO', 'Sin Contacto')], max_length=30, null=True)),
                ('fecha_firma', models.DateField(blank=True)),
                ('estado_diario', models.CharField(blank=True, choices=[('MOROSO', 'Moroso'), ('AL_DIA', 'Al Día')], max_length=50, null=True)),
                ('postergacion', models.BooleanField()),
                ('canal_ccl', models.BooleanField(verbose_name='Canal CCL')),
                ('canal_web', models.BooleanField(verbose_name='Canal WEB')),
                ('ejecutivo_cartera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pertenece_a_la_cartera', to='personas_beme.EjecutivoComercial')),
                ('ejecutivo_gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualmente_gestionando', to='personas_beme.EjecutivoComercial')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_oferta', models.DateField()),
                ('ope_tasa_oferta_1', models.FloatField(default=0)),
                ('plazo_oferta_1', models.IntegerField(default=1)),
                ('monto_oferta_1', models.IntegerField(default=0)),
                ('per_rebaja_oferta_1', models.FloatField(default=0)),
                ('total_a_pagar_oferta_1', models.IntegerField(default=0)),
                ('ope_tasa_oferta_2', models.FloatField(default=0)),
                ('plazo_oferta_2', models.IntegerField(default=1)),
                ('monto_oferta_2', models.IntegerField(default=0)),
                ('per_rebaja_oferta_2', models.FloatField(default=0)),
                ('total_a_pagar_oferta_2', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Oferta Cliente',
                'verbose_name_plural': 'Ofertas Clientes',
                'unique_together': {('fecha_de_oferta', 'cliente')},
            },
        ),
    ]
