# Generated by Django 2.2.10 on 2020-04-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='canal_ccl',
            field=models.IntegerField(blank=True, default=0, verbose_name='Canal CCL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='canal_web',
            field=models.IntegerField(blank=True, default=0, verbose_name='Canal WEB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_diario',
            field=models.CharField(blank=True, choices=[('MOROSO', 'Moroso'), ('AL_DIA', 'Al Día')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='postergacion',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=50),
            preserve_default=False,
        ),
    ]
