# Generated by Django 3.0.4 on 2020-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['cli_rut']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='respuesta_cliente',
            field=models.CharField(blank=True, choices=[('INTERESADO_ACEPTA_OFERTA_1_SIMULADOR', 'Interesado - Acepta Oferta 1 Simulador'), ('INTERESADO_ACEPTA_OFERTA_2_SIMULADOR', 'Interesado - Acepta Oferta 2 Simulador'), ('INTERESADO_OTRA_RENEGOCIACION', 'Interesado - Otra Renegociación'), ('INTERESADO_LO_PENSARA', 'Interesado - Lo Pensará'), ('RECHAZA_TOMARA_RENEGOCIACION_WEB', 'Rechaza - Tomará Renegociación Web'), ('RECHAZA_TOMARA_POSTERGACION', 'Rechaza - Tomará Postergación'), ('RECHAZA_PAGARA_CUOTA', 'Rechaza - Pagará Cuota'), ('RECHAZA_OTRO_MOTIVO', 'Rechaza - Otro Motivo'), ('SIN_CONTACTO_NO_CONTESTA_LLAMADA', 'Sin Contacto - No Contesta Llamada'), ('SIN_CONTACTO_Nº_NO_CORRESPONDE', 'Sin Contacto - N° No Corresponde'), ('SIN_CONTACTO_FONO_SIN_SERVICIO/NO_EXISTE', 'Sin Contacto - Fono Sin Servicio/No Existe'), ('LLAMAR_DURANTE_DIA', 'Llamar Durante el Día'), ('ACTUALIZACION_DATOS_CLIENTE', 'Actualización Datos Cliente'), ('INTERESADO_LLAMAR_OTRO_DIA', 'Interesado - Llamar otro Día')], max_length=100, null=True),
        ),
    ]
