# Generated by Django 2.2.10 on 2020-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='preaprobados_reng',
            field=models.BooleanField(default=False, verbose_name='Preaprobados Rene'),
            preserve_default=False,
        ),
    ]
