# Generated by Django 2.2.10 on 2020-05-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_preaprobados_reng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='canal_ccl',
            field=models.BooleanField(null=True, verbose_name='Canal CCL'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='canal_web',
            field=models.BooleanField(null=True, verbose_name='Canal WEB'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='postergacion',
            field=models.BooleanField(null=True),
        ),
    ]
