# Generated by Django 3.0.4 on 2020-06-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200608_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='n_gestiones',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='n_gestiones_efectivas',
            field=models.IntegerField(null=True),
        ),
    ]
