# Generated by Django 2.2.10 on 2020-04-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200429_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_diario',
            field=models.CharField(choices=[('MOROSO', 'Moroso'), ('AL_DIA', 'Al Día')], default='MOROSO', max_length=50),
            preserve_default=False,
        ),
    ]
