# Generated by Django 2.2.10 on 2020-05-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200510_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='canal_ccl',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=50, null=True, verbose_name='Canal CCL'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='postergacion',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=50, null=True),
        ),
    ]
