# Generated by Django 3.0.4 on 2020-06-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200608_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_regula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='max_otorgamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='max_proc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='monto_oto_vigente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ope_oto_vigente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sol_otorgada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
