# Generated by Django 2.2.10 on 2020-05-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200510_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='canal_ccl',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Canal CCL'),
        ),
    ]
