# Generated by Django 2.2.10 on 2020-04-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_impacto_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contactabilidad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_curse',
        ),
    ]
