# Generated by Django 3.0.4 on 2020-06-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200608_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='postergacion_cargada_hoy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
