# Generated by Django 2.2.10 on 2020-05-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20200510_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_c_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_c_oferta_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_gar_1_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_gar_1_oferta_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_gar_2_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_gar_2_oferta_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_gar_3_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_gar_3_oferta_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_gar_4_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_gar_4_oferta_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_k_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='monto_k_oferta_2',
            field=models.IntegerField(default=0),
        ),
    ]
