# Generated by Django 2.2.10 on 2020-04-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20200429_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='canal_ccl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Canal CCL'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='canal_web',
            field=models.IntegerField(blank=True, null=True, verbose_name='Canal WEB'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_comercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_particular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_contacto_interesado',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('SIN_CONTACTO', 'Sin Contacto')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_diario',
            field=models.CharField(blank=True, choices=[('MOROSO', 'Moroso'), ('AL_DIA', 'Al Día')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='postergacion',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='respuesta',
            field=models.CharField(blank=True, choices=[('INTERESADO_EN_OFERTA', 'Interesado en Oferta Simulador'), ('INTERESADO_EN_RENEGOCIAR', 'Interesado en Renegociar - Derivar a la Plataforma BEME'), ('NO_INTERESADO-PAGARA_CUOTA', 'No Interesado - Pagará Cuota')], max_length=30, null=True),
        ),
    ]
