# Generated by Django 2.2.10 on 2020-05-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20200510_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertacliente',
            name='eleccion_oferta',
            field=models.CharField(blank=True, choices=[('OFERTA_1', 'Oferta 1'), ('OFERTA_2', 'Oferta 2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='postergacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=50, null=True),
        ),
    ]
