# Generated by Django 2.2.10 on 2020-04-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20200429_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ejecutivo_cartera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pertenece_a_la_cartera', to='personas_beme.EjecutivoComercial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ejecutivo_gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualmente_gestionando', to='personas_beme.EjecutivoComercial'),
        ),
    ]
