# Generated by Django 2.2.10 on 2020-05-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20200510_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contactabilidad',
            field=models.CharField(blank=True, choices=[('CON_CONTACTO', 'Contactado'), ('SIN_CONTACTO', 'Sin Contacto')], max_length=50, null=True),
        ),
    ]
