# Generated by Django 2.2.10 on 2020-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20200507_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='postergacion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
