# Generated by Django 2.2.10 on 2020-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_cliente_estado_curse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='respuesta',
            new_name='respuesta_cliente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_curse',
            field=models.IntegerField(blank=True, choices=[('NO_CURSADA', 'No Cursada'), ('CURSADA', 'Cursada'), ('EN_PROCESO', 'En Proceso')], null=True),
        ),
    ]
