# Generated by Django 2.2.10 on 2020-05-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20200507_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='postergacion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
