# Generated by Django 2.2.10 on 2020-05-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20200507_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='canal_ccl',
            field=models.BooleanField(default=False, verbose_name='Canal CCL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='canal_web',
            field=models.BooleanField(default=False, verbose_name='Canal WEB'),
            preserve_default=False,
        ),
    ]
