# Generated by Django 2.2.10 on 2020-05-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20200511_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, choices=[('SE_ACERCARA', 'Se acercará a la Sucursal'), ('NO_SE_ACERCARA', 'No puede acercarse a la Sucursal'), ('LO_PENSARA', 'Lo Pensará')], max_length=30, null=True),
        ),
    ]
