# Generated by Django 2.2.10 on 2020-05-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_cliente_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='estado_contacto_interesado',
            new_name='contacto_cliente_interesado',
        ),
    ]
