# Generated by Django 2.2.10 on 2020-05-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20200511_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_cliente',
            field=models.CharField(blank=True, choices=[('FIMARA_DOCUMENTOS', 'Firmará Documentos'), ('DOCUMENTOS_FIRMADOS', 'Documentos Firmados'), ('RECHAZA_OFERTA', 'Rechaza Oferta')], max_length=30, null=True),
        ),
    ]
