# Generated by Django 2.2.10 on 2020-05-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_cliente_estado_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, choices=[('SE_ACERCARA_A_SUCURSAL', 'Se acercará a la Sucursal'), ('NO_PUEDE_ACERCARSE_A_SUCURSAL ', 'No puede acercarse a la Sucursal'), ('LO_PENSARA', 'Lo Pensará')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_cliente',
            field=models.CharField(blank=True, choices=[('FIRMARA_DOCUMENTOS', 'Firmará Documentos'), ('DOCUMENTOS_FIRMADOS', 'Documentos Firmados'), ('RECHAZA_OFERTA', 'Rechaza Oferta')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='respuesta_cliente',
            field=models.CharField(blank=True, choices=[('INTERESADO_EN_OFERTA_SIMULADOR', 'Interesado en Oferta Simulador'), ('INTERESADO_EN_RENEGOCIAR_-_DERIVAR_A_PLATAFORMA_BEME', 'Interesado en Renegociar - Derivar a la Plataforma BEME'), ('NO_INTERESADO_-_PAGARA_CUOTA', 'No Interesado - Pagará Cuota')], max_length=30, null=True),
        ),
    ]
