# Generated by Django 2.2.10 on 2020-05-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_auto_20200511_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertacliente',
            old_name='plazo_oferta_1',
            new_name='num_cuotas_oferta_1',
        ),
        migrations.RenameField(
            model_name='ofertacliente',
            old_name='plazo_oferta_2',
            new_name='num_cuotas_oferta_2',
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='num_cuotas_gar_1_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='num_cuotas_gar_1_oferta_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='num_cuotas_gar_2_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='num_cuotas_gar_2_oferta_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='num_cuotas_gar_3_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='num_cuotas_gar_4_oferta_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='num_cuotas_gar_4_oferta_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertacliente',
            name='num_cuotas_k_1',
            field=models.IntegerField(default=0),
        ),
    ]
