# Generated by Django 2.2.10 on 2020-05-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20200513_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertacliente',
            name='num_cuotas_k_2',
            field=models.IntegerField(default=0),
        ),
    ]
