# Generated by Django 2.2.10 on 2020-05-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_ofertacliente_num_cuotas_k_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ejecutivo_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualmente_gestionando', to='personas_beme.EjecutivoComercial'),
        ),
        migrations.AlterField(
            model_name='ofertacliente',
            name='num_cuotas_oferta_1',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
