# Generated by Django 2.2.10 on 2020-05-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas_beme', '0003_auto_20200515_1128'),
        ('clientes', '0018_auto_20200515_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ejecutivo_gestor',
        ),
        migrations.AddField(
            model_name='cliente',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualmente_gestionando', to='personas_beme.Persona'),
        ),
    ]
