# Generated by Django 2.2.10 on 2020-05-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_auto_20200515_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_curse',
            field=models.CharField(blank=True, choices=[('NO_CURSADA', 'No Cursada'), ('CURSADA', 'Cursada'), ('EN_PROCESO', 'En Proceso')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_gestion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
