# Generated by Django 2.2.10 on 2020-05-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_auto_20200518_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_firma',
            field=models.DateField(blank=True, null=True),
        ),
    ]
