# Generated by Django 2.2.10 on 2020-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_auto_20200519_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='disponibilidad_oferta',
            field=models.BooleanField(verbose_name='Disponibilidad de Ofertasxxs'),
        ),
    ]
