# Generated by Django 2.2.10 on 2020-05-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_auto_20200519_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='clientes.Cliente'),
        ),
    ]
