# Generated by Django 2.2.10 on 2020-05-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_auto_20200520_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='disponibilidad_oferta',
            field=models.BooleanField(verbose_name='Disponibilidad de Ofertas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_curse',
            field=models.CharField(blank=True, choices=[('NO_CURSADA', 'No Cursada'), ('EN_PROCESO', 'En Proceso'), ('ENVIADA_A_CURSE', 'Enviada a Curse')], max_length=30, null=True),
        ),
    ]
