# Generated by Django 2.2.10 on 2020-04-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasaSeguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazo', models.CharField(choices=[('[1  , 12]', '[1  , 12]'), ('[13 , 24]', '[13 , 24]'), ('[25 , 36]', '[25 , 36]'), ('[37 , 48]', '[37 , 48]'), ('[49 , 60]', '[49 , 60]'), ('[61 , 72]', '[61 , 72]'), ('[73 , 84]', '[73 , 84]'), ('[85 , 96]', '[85 , 96]'), ('[97 , 108]', '[97 , 108]'), ('[109, 120]', '[109, 120]')], max_length=30)),
                ('valor_tasa', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Tasa Seguro',
                'verbose_name_plural': 'Tasas Seguro',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('valor_uf', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UF',
            },
        ),
    ]
