# Generated by Django 2.2.10 on 2020-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_complementaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoGracia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_de_gracia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TasaOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ope_tasa', models.FloatField(default=0, help_text='Debe estar en porcentaje %')),
            ],
        ),
    ]
