# Generated by Django 2.2.10 on 2020-05-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_complementaria', '0002_periodogracia_tasaoferta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodogracia',
            options={'verbose_name': 'Periodo de Gracia', 'verbose_name_plural': 'Periodos de Gracia'},
        ),
        migrations.AlterModelOptions(
            name='tasaoferta',
            options={'verbose_name': 'Tasa de Oferta', 'verbose_name_plural': 'Tasas de Oferta'},
        ),
    ]
